version: "3.7"

services:
  postgres:
    container_name: posterr_Database
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-jean}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-posterr}
      POSTGRES_DB: ${POSTGRES_DB:-posterr-backend}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
